/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd1801.Buoi5;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Syn
 */
public class DemoTableBanhTrungThu extends javax.swing.JFrame {

    /**
     * Creates new form DemoTableBanhTrungThu
     */
    // Tạo ArrayList<BanhTrungThu> và thêm 3 phần tử mới vào trong ArrayList    
    public DemoTableBanhTrungThu() {
        initComponents();
        
        ArrayList<BanhTrungThu> listBanh = new ArrayList<>();
        listBanh.add(new BanhTrungThu(1, "Thap cam", 4.5f, "Yen xao ngu vi"));
        listBanh.add(new BanhTrungThu(2, "Banh deo", 5.5f, "Lava trung chay"));
        listBanh.add(new BanhTrungThu(3, "Dau xanh", 6.5f, "Mot trung muoi"));
        // Goi ham fillTableData
        fillTableData(listBanh);
    }

    public void fillTableData(ArrayList<BanhTrungThu> danhSach) {
        // su dung danhSach de fill du lieu len bang
        DefaultTableModel model = (DefaultTableModel) tblBanh.getModel();
        for(BanhTrungThu banh: danhSach) {
            model.addRow(new Object[]{banh.getId(), banh.getTen(), banh.getGia(), banh.getLoaiNhan()});
        }
        tblBanh.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanh = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ten", "Gia", "Loai Nhan"
            }
        ));
        jScrollPane1.setViewportView(tblBanh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoTableBanhTrungThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoTableBanhTrungThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoTableBanhTrungThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoTableBanhTrungThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoTableBanhTrungThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBanh;
    // End of variables declaration//GEN-END:variables
}
